name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@develop
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
